<div>
<a class="text-link" href="{{ route('enrollments') }}">Voltar às matrículas</a>
<div class="page-heading"><div><span class="eyebrow">MATRÍCULA #{{ $enrollment->id }} · {{ $enrollment->academicYear->year }}</span><h1>{{ $enrollment->student->name }}</h1><p>Uma matrícula anual, com os períodos de atendimento preservados.</p></div><span class="badge {{ $enrollment->status==='APROVADA' ? 'green':'neutral' }}">{{ $enrollment->status_label }}</span></div>
@if($errors->any())<div class="notice error" role="alert"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@if($enrollment->closed_on)<div class="notice" role="status">{{ $enrollment->closure_type==='CANCELAMENTO' ? 'Cancelamento':'Encerramento' }} a partir de {{ $enrollment->closed_on->format('d/m/Y') }}. Os atendimentos anteriores permanecem no histórico.</div>@endif
@if($mode==='')<div class="enrollment-actions">
@if($enrollment->status==='RASCUNHO')@can('matriculas.editar')<button class="button secondary" wire:click="begin('edit')">Editar rascunho</button>@endcan
@elseif(!$enrollment->closed_on && $current && $current->ends_on->gte(today()))@can('matriculas.aprovar')<button class="button secondary" wire:click="begin('transfer')">Transferir atendimento</button><button class="button subtle" wire:click="begin('close')">Encerrar / cancelar</button>@endcan @endif
</div>@endif
@if(in_array($mode,['edit','transfer']))<section class="panel form-panel"><div class="panel-heading"><h2>{{ $mode==='edit' ? 'Editar rascunho':'Transferir atendimento' }}</h2><button class="button subtle" wire:click="cancel">Cancelar</button></div><p class="footnote">{{ $mode==='edit' ? 'Salvar cria uma nova versão do rascunho e exige anexar o termo correspondente.':'A data inicial será o primeiro dia do novo atendimento. O período anterior terminará no dia precedente. Anexe e confira o termo correspondente à transferência.' }}</p><form wire:submit="save">@include('livewire.enrollment-form',['identityEditable'=>false])
@if($mode==='transfer')<div class="field"><label for="transfer-term">Termo da transferência assinado pelo GOV.BR (PDF, até 10 MB)</label><input id="transfer-term" type="file" accept="application/pdf,.pdf" wire:model="term" required></div><label class="enrollment-check"><input type="checkbox" wire:model="reviewed" required><span>Conferi os dados, a assinatura GOV.BR do responsável e a correspondência do termo com este atendimento.</span></label>@endif
<div class="form-actions"><button class="button primary" wire:loading.attr="disabled">{{ $mode==='edit' ? 'Salvar nova versão':'Confirmar transferência' }}</button></div><p wire:loading wire:target="term">Enviando termo…</p></form></section>@endif
@if($mode==='close')<section class="panel form-panel"><div class="panel-heading"><h2>Registrar término</h2><button class="button subtle" wire:click="cancel">Voltar</button></div><form wire:submit="close"><div class="form-grid"><div class="field"><label for="closure-date">Primeiro dia sem transporte</label><input id="closure-date" type="date" wire:model="effectiveFrom" min="{{ today()->toDateString() }}" required></div><div class="field"><label for="closure-type">Tipo de término</label><select id="closure-type" wire:model="closureType"><option value="ENCERRAMENTO">Encerramento</option><option value="CANCELAMENTO">Cancelamento</option></select></div><div class="field full-width"><label for="closure-reason">Justificativa</label><textarea id="closure-reason" wire:model="reason" required minlength="10" maxlength="1000"></textarea></div></div><p class="footnote">A data libera as vagas deste aluno em todas as operações vinculadas. O registro não pode ser apagado ou reaberto nesta versão.</p><div class="form-actions"><button class="button primary" wire:loading.attr="disabled">Confirmar término</button></div></form></section>@endif
@if($enrollment->status==='RASCUNHO' && $mode==='')
<section class="panel form-panel"><div class="panel-heading"><h2>Termo e aprovação</h2></div><p>O termo deve ser assinado externamente pelo responsável no GOV.BR. O envio não efetiva a matrícula.</p>
@if(!$current?->term_path)@can('matriculas.editar')<form wire:submit="attach"><div class="field"><label for="signed-term">Anexar termo assinado (PDF, até 10 MB)</label><input id="signed-term" type="file" accept="application/pdf,.pdf" wire:model="term" required></div><div class="form-actions"><button class="button secondary" wire:loading.attr="disabled">Anexar para análise</button></div><p wire:loading wire:target="term">Enviando termo…</p></form>@endcan
@else<p><strong>Termo anexado.</strong> @can('matriculas.documentos')<a class="text-link" href="{{ route('enrollments.term',[$enrollment->id,$current->id]) }}">Baixar para conferência</a>@endcan</p>@endif
@can('matriculas.aprovar')<form wire:submit="approve"><label class="enrollment-check"><input type="checkbox" wire:model="reviewed" required><span>Conferi os dados, a assinatura GOV.BR do responsável e a correspondência do termo com esta matrícula.</span></label><p class="footnote">A conferência da assinatura é realizada pelo servidor responsável. O sistema verifica formato e integridade do arquivo.</p><div class="field"><label for="approval-reason">Parecer administrativo</label><textarea id="approval-reason" wire:model="reason" required minlength="10" maxlength="1000" rows="2"></textarea></div><div class="form-actions"><button class="button primary" wire:loading.attr="disabled" @disabled(!$current?->term_path)>Aprovar e reservar vagas</button></div></form>@else<p class="footnote">Aguardando conferência por servidor com permissão para aprovar matrículas.</p>@endcan
</section>@endif
<section class="panel"><div class="panel-heading"><h2>Períodos de atendimento e versões</h2></div><div class="table-scroll"><table><thead><tr><th>Período</th><th>Oferta escolar e responsável</th><th>Transporte</th><th>Termo e conferência</th></tr></thead><tbody>
@foreach($enrollment->periods->sortByDesc('id') as $period)<tr wire:key="period-{{ $period->id }}"><td><strong>#{{ $period->id }}</strong><br>{{ $period->starts_on->format('d/m/Y') }} a {{ $period->ends_on->format('d/m/Y') }}<br>@if($period->cancelled_at)<span class="badge neutral">Versão sem atendimento</span>@elseif($enrollment->status==='RASCUNHO')<span class="badge neutral">Rascunho · sem reserva</span>@elseif($period->ends_on->lt(today()))<span class="badge neutral">Histórico</span>@elseif($period->starts_on->gt(today()))<span class="badge green">Programado</span>@else<span class="badge green">Vigente</span>@endif @if(!$period->ends_on->equalTo($period->original_ends_on))<br><small>Término original: {{ $period->original_ends_on->format('d/m/Y') }}</small>@endif</td><td><strong>{{ $period->school->name }}</strong><br>{{ $period->grade->name }} · {{ $period->shift->name }}<br><small>Responsável: {{ $period->guardian->name }}</small></td><td>@foreach($period->operations as $op)<p>@can('transporte.visualizar')<a class="text-link" href="{{ route('transport.operation',$op->id) }}">{{ $op->routeLine->code }} · {{ $op->name }}</a>@else{{ $op->routeLine->code }} · {{ $op->name }}@endcan<br><small>{{ substr($op->starts_at,0,5) }}–{{ substr($op->ends_at,0,5) }}</small></p>@endforeach</td><td>@if($period->term_path)@can('matriculas.documentos')<a class="text-link" href="{{ route('enrollments.term',[$enrollment->id,$period->id]) }}">Baixar termo</a>@else Termo anexado @endcan @else Sem termo @endif @if($period->reviewed_at)<br><small>Conferido por {{ $period->reviewer->name }} em {{ $period->reviewed_at->format('d/m/Y H:i') }}</small>@endif</td></tr>@endforeach
</tbody></table></div></section>
<section class="panel recent-panel"><div class="panel-heading"><h2>Histórico administrativo</h2></div>@foreach($events as $event)<div class="activity-row"><span class="activity-dot"></span><div><strong>{{ str_replace('_',' ',ucfirst($event->action)) }}</strong><small>{{ $event->actor?->name ?? 'Sistema' }} · {{ $event->reason }}</small></div><time>{{ $event->created_at->format('d/m/Y H:i') }}</time></div>@endforeach</section>
</div>
