<div>
<a class="text-link" href="{{ route('transport','operacoes') }}">← Voltar às operações</a>
<div class="page-heading"><div><span class="eyebrow">TRANSPORTE · {{ $operation->routeLine->code }}</span><h1>{{ $operation->name }}</h1><p>{{ $operation->routeLine->name }} · {{ $operation->academicYear->year }} · {{ $operation->shift->name }}</p></div><span class="badge {{ $operation->status==='ATIVA'?'green':'neutral' }}">{{ $operation->status==='ATIVA'?'Ativa':'Inativa' }}</span></div>
<section class="panel form-panel">
<div class="operation-facts"><div><small>Vigência</small><strong>{{ $operation->starts_on->format('d/m/Y') }} a {{ $operation->ends_on->format('d/m/Y') }}</strong></div><div><small>Horário</small><strong>{{ substr($operation->starts_at,0,5) }} – {{ substr($operation->ends_at,0,5) }}</strong></div><div><small>Dias de atendimento</small><strong>{{ collect($operation->weekdays)->map(fn($d)=>config('transport.weekdays.'.$d))->join(', ') }}</strong></div></div>
<div class="capacity-summary"><div class="field"><label for="capacity-date">Consultar capacidade na data</label><input type="date" id="capacity-date" wire:model.live="date"></div><div><small>{{ $capacity['label'] }}</small><strong class="capacity-number">{{ $capacity['seats'] ?? '—' }} @if($capacity['seats']!==null)<span>alunos</span>@endif</strong>@if($capacity['allocation'])<span>Veículo {{ $capacity['allocation']->vehicle->plate }}</span>@endif</div></div>
@if($capacity['warning'])<div class="notice error" role="status">{{ $capacity['warning'] }}</div>@endif
<div class="operation-facts"><div><small>Matrículas na data</small><strong>{{ $capacity['occupied'] ?? '—' }}</strong></div><div><small>Vagas previstas na data</small><strong>{{ $capacity['available'] ?? '—' }}</strong></div></div>
<p class="footnote">A ocupação considera matrículas aprovadas e seus períodos de atendimento. As vagas seguem a capacidade registrada na alocação e a programação semanal, sem calendário de feriados. Rascunhos não reservam vaga; alertas de indisponibilidade exigem regularização da frota.</p>
</section>
@can('alocacoes.gerenciar')
@if($operation->status==='ATIVA' && $operation->ends_on->gte(today()))
<section class="panel form-panel"><div class="panel-heading"><h2>Alocar veículo</h2></div><p class="footnote">Um veículo por operação em cada período. Horários conflitantes em outras operações são bloqueados.</p>
<form wire:submit="allocate"><div class="form-grid">
<div class="field full-width"><label for="allocation-vehicle">Veículo</label><select id="allocation-vehicle" wire:model="allocation.vehicle_id" required><option value="">Selecione um veículo</option>@foreach($vehicles as $v)<option value="{{ $v->id }}">{{ $v->plate }} · {{ $v->model }} · {{ $v->capacity }} alunos</option>@endforeach</select>@error('allocation.vehicle_id')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div>
<div class="field"><label for="allocation-start">Início da alocação</label><input type="date" id="allocation-start" wire:model="allocation.starts_on" min="{{ max(today()->format('Y-m-d'),$operation->starts_on->format('Y-m-d')) }}" max="{{ $operation->ends_on->format('Y-m-d') }}" required>@error('allocation.starts_on')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div>
<div class="field"><label for="allocation-end">Fim da alocação</label><input type="date" id="allocation-end" wire:model="allocation.ends_on" max="{{ $operation->ends_on->format('Y-m-d') }}" required>@error('allocation.ends_on')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div>
<div class="field full-width"><label for="allocation-reason">Justificativa</label><textarea id="allocation-reason" wire:model="allocation.reason" required minlength="10" maxlength="1000" rows="2"></textarea>@error('allocation.reason')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div>
</div>@error('allocation.form')<div class="notice error" role="alert">{{ $message }}</div>@enderror<div class="form-actions"><button class="button primary" wire:loading.attr="disabled" wire:target="allocate">Alocar veículo</button></div></form></section>
@endif
@if($releaseId)
<section class="panel form-panel"><div class="panel-heading"><h2>Liberar alocação #{{ $releaseId }}</h2><button class="button subtle" wire:click="cancelRelease">Cancelar</button></div>
<p class="footnote">A data informada será o primeiro dia sem este veículo. Se houver matrículas, selecione um substituto com capacidade suficiente. A substituição e a liberação serão confirmadas juntas.</p>
<div class="field"><label for="release-replacement">Veículo substituto</label><select id="release-replacement" wire:model="replacementVehicleId"><option value="">Somente liberar (exige ausência de matrículas)</option>@foreach($vehicles as $v)<option value="{{ $v->id }}">{{ $v->plate }} · {{ $v->capacity }} lugares</option>@endforeach</select>@error('release.replacement_vehicle_id')<span class="field-error" role="alert">{{ $message }}</span>@enderror @error('release.operation_ids')<span class="field-error" role="alert">{{ $message }}</span>@enderror @error('release.vehicle_id')<span class="field-error" role="alert">{{ $message }}</span>@enderror @error('release.starts_on')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div>
<form wire:submit="release"><div class="form-grid"><div class="field"><label for="release-date">Liberar a partir de</label><input type="date" id="release-date" wire:model="effectiveFrom" min="{{ today()->format('Y-m-d') }}" required>@error('release.effective_from')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div><div class="field"><label for="release-reason">Motivo da liberação</label><textarea id="release-reason" wire:model="releaseReason" required minlength="10" maxlength="1000" rows="2"></textarea>@error('release.reason')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div></div>@error('release.form')<div class="notice error" role="alert">{{ $message }}</div>@enderror<div class="form-actions"><button class="button primary" wire:loading.attr="disabled" wire:target="release">Confirmar liberação</button></div></form></section>
@endif
@endcan
<section class="panel"><div class="table-toolbar"><div class="table-title"><h2>Histórico de alocações</h2><span class="count-pill">{{ $allocations->total() }}</span></div></div>
<div class="table-scroll"><table><thead><tr><th>Veículo</th><th>Período</th><th>Capacidade registrada</th><th>Registro e justificativas</th><th>Ações</th></tr></thead><tbody>
@forelse($allocations as $a)<tr wire:key="allocation-{{ $a->id }}"><td><strong>{{ $a->vehicle->plate }}</strong><br>{{ $a->vehicle->model }}<br><small>Situação atual: {{ config('transport.resources.veiculos.fields.status.options.'.$a->vehicle->status) }}</small></td><td>{{ $a->starts_on->format('d/m/Y') }} a {{ $a->ends_on->format('d/m/Y') }}<br>@if($a->cancelled_at)<span class="badge neutral">Cancelada</span>@elseif($a->ends_on->lt(today()))<span class="badge neutral">Encerrada</span>@elseif($a->starts_on->gt(today()))<span class="badge green">Programada</span>@else<span class="badge green">Vigente</span>@endif @if($a->released_at)<br><small>Término original: {{ $a->original_ends_on->format('d/m/Y') }}</small>@endif</td><td>{{ $a->capacity_snapshot }} alunos</td><td class="allocation-notes"><strong>{{ $a->creator->name }}</strong><small> · {{ $a->created_at->format('d/m/Y H:i') }}</small><p>{{ $a->reason }}</p>@if($a->released_at)<p>Liberação: {{ $a->release_reason }}</p><small>{{ $a->releaser->name }} · {{ $a->released_at->format('d/m/Y H:i') }}</small>@endif</td><td>@can('alocacoes.gerenciar')@if(!$a->cancelled_at && $a->ends_on->gte(today()))<button class="text-link" wire:click="beginRelease({{ $a->id }})">Liberar / substituir</button>@endif @endcan</td></tr>
@empty<tr><td colspan="5"><div class="empty-state"><x-icon name="bus"/><h3>Nenhum veículo alocado</h3><p>Selecione um veículo e informe o período de atendimento.</p></div></td></tr>@endforelse
</tbody></table></div>@include('components.pagination',['paginator'=>$allocations])</section>
</div>
