<div>
<div class="page-heading"><div><span class="eyebrow">ALUNOS E FAMÍLIAS</span><h1>{{ $definition['title'] }}</h1><p>{{ $resource === 'alunos' ? 'Cadastre os alunos e organize os responsáveis por cada um.' : 'Mantenha os dados de contato e acompanhe os alunos vinculados.' }}</p></div>
@can('pessoas.editar')<button class="button primary" wire:click="create"><x-icon name="plus"/> Novo {{ $definition['singular'] }}</button>@endcan</div>
@if($showForm)
<section class="panel form-panel"><div class="panel-heading"><h2>{{ $editingId ? 'Editar' : 'Cadastrar' }} {{ $definition['singular'] }}</h2><button class="button subtle" wire:click="cancel">Fechar</button></div>
<form wire:submit="save"><div class="form-grid">
<div class="field full-width"><label for="person-name">Nome completo *</label><input id="person-name" wire:model="form.name" required maxlength="150" autocomplete="off">@error('form.name')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div>
<div class="field"><label for="person-cpf">CPF</label><input id="person-cpf" wire:model="form.cpf" inputmode="numeric" maxlength="14" placeholder="000.000.000-00" autocomplete="off"><small>Quando informado, será validado para evitar duplicidade.</small>@error('form.cpf')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div>
<div class="field"><label for="person-birth">Data de nascimento {{ $resource === 'alunos' ? '*' : '' }}</label><input id="person-birth" type="date" wire:model="form.birth_date" max="{{ today()->toDateString() }}" min="1900-01-01" @required($resource==='alunos')>@error('form.birth_date')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div>
@if($resource==='responsaveis')
<div class="field"><label for="person-phone">Telefone</label><input id="person-phone" type="tel" wire:model="form.phone" maxlength="20" autocomplete="off">@error('form.phone')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div>
<div class="field"><label for="person-email">E-mail</label><input id="person-email" type="email" wire:model="form.email" maxlength="255" autocomplete="off">@error('form.email')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div>
@endif
<div class="field full-width"><label class="checkbox-label"><input type="checkbox" wire:model="form.active"> Cadastro ativo</label><small>Um cadastro inativo impede novas solicitações de transporte, mesmo com vínculo autorizado.</small>@error('form.active')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div>
@if($editingId)<div class="field full-width"><label for="person-reason">Justificativa da alteração *</label><textarea id="person-reason" wire:model="reason" required minlength="10" maxlength="1000" rows="2" placeholder="Explique por que o cadastro está sendo alterado."></textarea>@error('reason')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div>@endif
</div>@error('form')<div class="notice error" role="alert">{{ $message }}</div>@enderror
<div class="form-actions"><button type="button" class="button secondary" wire:click="cancel">Cancelar</button><button class="button primary" wire:loading.attr="disabled" wire:target="save">Salvar cadastro</button></div>
</form></section>
@endif
<section class="panel"><div class="table-toolbar"><div class="table-title"><h2>{{ $definition['title'] }} cadastrados</h2><span class="count-pill">{{ $records->total() }}</span></div><div class="filters"><div class="search-input"><x-icon name="search"/><input type="search" wire:model.live.debounce.300ms="search" placeholder="Buscar nome ou CPF completo..." aria-label="Buscar nome ou CPF completo"></div><select wire:model.live="status" aria-label="Filtrar situação"><option value="active">Ativos</option><option value="inactive">Inativos</option><option value="">Todas as situações</option></select></div></div>
<div class="table-scroll"><table><thead><tr><th>Nome</th><th>CPF</th><th>Nascimento</th><th>{{ $resource==='alunos' ? 'Responsáveis' : 'Alunos' }}</th><th>Situação</th><th class="align-right">Ações</th></tr></thead>
<tbody>@forelse($records as $record)<tr wire:key="person-{{ $record->id }}"><td><a class="person-name-link" href="{{ route('people.show',[$resource,$record->id]) }}">{{ $record->name }}</a>@if($resource==='responsaveis' && $record->phone)<small class="cell-subtitle">{{ $record->phone }}</small>@endif</td><td class="nowrap">{{ $record->masked_cpf }}</td><td>{{ $record->birth_date?->format('d/m/Y') ?? 'Não informada' }}</td><td>{{ $record->current_links_count }} {{ $record->current_links_count===1 ? 'vínculo vigente' : 'vínculos vigentes' }}</td><td><span class="badge {{ $record->active ? 'green':'neutral' }}">{{ $record->active ? 'Ativo':'Inativo' }}</span></td><td><div class="row-actions"><a class="text-link" href="{{ route('people.show',[$resource,$record->id]) }}">Abrir ficha</a>@can('pessoas.editar')<button class="text-link" wire:click="edit({{ $record->id }})">Editar</button>@endcan</div></td></tr>
@empty<tr><td colspan="6"><div class="empty-state"><x-icon name="users"/><h3>Nenhum cadastro encontrado</h3><p>{{ $search ? 'Tente outro nome ou o CPF completo.' : 'Cadastre o primeiro registro para começar a organizar os vínculos.' }}</p></div></td></tr>@endforelse</tbody></table></div>
@include('components.pagination',['paginator'=>$records])</section>
<p class="footnote"><x-icon name="shield"/> O cadastro não efetiva uma matrícula. A solicitação e a análise de transporte serão tratadas em uma etapa própria.</p>
</div>
