<div>
<a class="text-link profile-back" href="{{ route('people',$resource) }}">← Voltar para {{ $resource==='alunos' ? 'alunos' : 'responsáveis' }}</a>
<div class="page-heading"><div><span class="eyebrow">{{ $resource==='alunos' ? 'FICHA DO ALUNO' : 'FICHA DO RESPONSÁVEL' }}</span><h1>{{ $person->name }}</h1><p>Dados cadastrais, vínculos e histórico em um só lugar.</p></div><span class="badge {{ $person->active ? 'green':'neutral' }}">{{ $person->active ? 'Cadastro ativo':'Cadastro inativo' }}</span></div>
<section class="panel profile-summary"><div><small>CPF</small><strong>{{ $person->masked_cpf }}</strong></div><div><small>Nascimento</small><strong>{{ $person->birth_date?->format('d/m/Y') ?? 'Não informado' }}</strong></div>
@if($resource==='responsaveis')<div><small>Telefone</small><strong>{{ $person->phone ?: 'Não informado' }}</strong></div><div><small>E-mail</small><strong>{{ $person->email ?: 'Não informado' }}</strong></div>@else<div><small>Cadastro</small><strong>#{{ str_pad($person->id,5,'0',STR_PAD_LEFT) }}</strong></div><div><small>Cadastrado em</small><strong>{{ $person->created_at->format('d/m/Y') }}</strong></div>@endif</section>
@if(!$person->active)<div class="notice">Este cadastro está inativo. Seus vínculos são preservados, mas não autorizam novas solicitações.</div>@endif
<div class="profile-toolbar"><div class="profile-tabs" role="group" aria-label="Conteúdo da ficha"><button class="{{ $tab==='current' ? 'active':'' }}" wire:click="$set('tab','current')">Vínculos vigentes</button><button class="{{ $tab==='links-history' ? 'active':'' }}" wire:click="$set('tab','links-history')">Histórico de vínculos</button><button class="{{ $tab==='changes' ? 'active':'' }}" wire:click="$set('tab','changes')">Alterações cadastrais</button></div>
@if($resource==='alunos' && $person->active)@can('vinculos.gerenciar')<button class="button primary" wire:click="addLink"><x-icon name="plus"/> Vincular responsável</button>@endcan @endif</div>

@if($showLinkForm)<section class="panel form-panel"><div class="panel-heading"><h2>{{ $editingLinkId ? 'Alterar vínculo' : 'Vincular responsável' }}</h2><button class="button subtle" wire:click="cancelLink">Fechar</button></div>
<form wire:submit="saveLink"><div class="form-grid">
@if(!$editingLinkId)<div class="field full-width"><label for="guardian-search">Localizar responsável</label><input id="guardian-search" wire:model.live.debounce.300ms="guardianSearch" type="search" placeholder="Busque por nome ou CPF completo"><small>São exibidos até 30 responsáveis ativos. Use a busca para localizar outro cadastro.</small></div>@endif
<div class="field full-width"><label for="guardian-select">Responsável *</label><select id="guardian-select" wire:model="guardianId" @disabled($editingLinkId!==null) required><option value="">Selecione um responsável</option>@foreach($guardians as $guardian)<option value="{{ $guardian->id }}">{{ $guardian->name }} · {{ $guardian->masked_cpf }}</option>@endforeach</select>@error('guardianId')<span class="field-error" role="alert">{{ $message }}</span>@enderror
@if(!$editingLinkId)<small>Não encontrou? @can('pessoas.editar')<a class="text-link" href="{{ route('people','responsaveis') }}">Cadastre o responsável</a>@else Solicite o cadastro à equipe autorizada.@endcan</small>@endif</div>
<div class="field"><label for="relationship">Tipo de vínculo *</label><select id="relationship" wire:model="relationship">@foreach(config('people.relationships') as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select>@error('relationship')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div>
<div class="field"><label class="checkbox-label"><input type="checkbox" wire:model="is_primary"> Responsável principal</label><small>Somente um vínculo vigente pode ser principal.</small>@error('is_primary')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div>
<div class="field full-width"><label class="checkbox-label"><input type="checkbox" wire:model="can_request"> Autorizar este responsável a solicitar transporte</label><small>Marque apenas após a conferência administrativa do vínculo.</small>@error('can_request')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div>
<div class="field full-width"><label for="link-reason">Justificativa / registro da conferência *</label><textarea id="link-reason" wire:model="reason" minlength="10" maxlength="1000" required rows="2"></textarea>@error('reason')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div>
</div>@error('link')<div class="notice error" role="alert">{{ $message }}</div>@enderror
<div class="form-actions"><button type="button" class="button secondary" wire:click="cancelLink">Cancelar</button><button class="button primary" wire:loading.attr="disabled" wire:target="saveLink">Salvar vínculo</button></div></form></section>@endif

@if($endingLinkId)<section class="panel form-panel"><div class="panel-heading"><h2>Encerrar vínculo</h2></div><form wire:submit="endLink"><p class="muted">O vínculo deixará de autorizar novas solicitações. O histórico será mantido.</p><div class="field"><label for="end-reason">Motivo do encerramento *</label><textarea id="end-reason" wire:model="endReason" required minlength="10" maxlength="1000" rows="2"></textarea>@error('endReason')<span class="field-error" role="alert">{{ $message }}</span>@enderror</div>@error('link')<div class="notice error" role="alert">{{ $message }}</div>@enderror<div class="form-actions"><button type="button" class="button secondary" wire:click="cancelLink">Cancelar</button><button class="button primary" wire:loading.attr="disabled">Confirmar encerramento</button></div></form></section>@endif

@if($tab==='changes')
<section class="panel"><div class="panel-heading"><div><h2>Alterações cadastrais</h2><p>Versões preservadas desde o primeiro cadastro.</p></div></div>
@forelse($revisions as $revision)<details class="revision-entry" wire:key="revision-{{ $revision->id }}"><summary><span>{{ $revision->created_at->format('d/m/Y H:i') }} · {{ $revision->actor?->name ?? 'Usuário' }}</span><span class="badge neutral">{{ count($revision->changes) }} campos</span></summary><div class="revision-body">
<div class="table-scroll"><table><thead><tr><th>Campo</th><th>Antes</th><th>Depois</th></tr></thead><tbody>@foreach($revision->changes as $field=>$values)<tr><td>{{ config('people.labels.'.$field,$field) }}</td>@foreach(['before','after'] as $side)<td>@if($values[$side]===null) — @elseif($field==='cpf'){{ \App\Support\Cpf::masked($values[$side]) }}@elseif($field==='active'){{ $values[$side] ? 'Ativo':'Inativo' }}@elseif($field==='birth_date'){{ \Carbon\Carbon::parse($values[$side])->format('d/m/Y') }}@else{{ $values[$side] }}@endif</td>@endforeach</tr>@endforeach</tbody></table></div><p class="revision-reason">{{ $revision->reason ?: 'Cadastro inicial.' }}</p></div></details>
@empty<div class="empty-state"><x-icon name="clock"/><h3>Nenhuma alteração registrada</h3><p>As próximas alterações aparecerão nesta ficha.</p></div>@endforelse
@include('components.pagination',['paginator'=>$revisions])</section>
@else
<section class="panel"><div class="panel-heading"><div><h2>{{ $tab==='links-history' ? 'Todas as versões dos vínculos' : ($resource==='alunos' ? 'Responsáveis vinculados' : 'Alunos vinculados') }}</h2><p>{{ $tab==='links-history' ? 'Vigências encerradas continuam disponíveis para consulta.' : 'Confira o vínculo e a autorização para solicitar transporte.' }}</p></div></div>
<div class="table-scroll"><table><thead><tr><th>{{ $resource==='alunos' ? 'Responsável':'Aluno' }}</th><th>Vínculo</th><th>Vigência</th><th>Autorização</th><th>Registro</th><th>Ações</th></tr></thead><tbody>
@forelse($links as $link)@php($related=$resource==='alunos' ? $link->guardian : $link->student)
<tr wire:key="link-{{ $link->id }}"><td><a class="person-name-link" href="{{ route('people.show',[$resource==='alunos' ? 'responsaveis':'alunos',$related->id]) }}">{{ $related->name }}</a><small class="cell-subtitle">{{ $related->active ? 'Cadastro ativo':'Cadastro inativo' }}</small></td><td>{{ config('people.relationships.'.$link->relationship) }}@if($link->is_primary)<small class="cell-subtitle">Responsável principal</small>@endif</td><td><span class="nowrap">{{ $link->started_at->format('d/m/Y H:i') }}</span><small class="cell-subtitle">{{ $link->ended_at ? 'Até '.$link->ended_at->format('d/m/Y H:i') : 'Vigente' }}</small></td>
<td>@if($link->ended_at)<span class="badge neutral">Encerrado</span>@elseif($link->permitsRequest())<span class="badge green">Autorizado</span>@else<span class="badge neutral">{{ $link->can_request ? 'Cadastro inativo':'Não autorizado' }}</span>@endif</td>
<td><details><summary>Ver registro</summary><div class="audit-details"><strong>Registrado por {{ $link->creator?->name }}</strong><p>{{ $link->reason }}</p>@if($link->ended_at)<strong>Encerrado por {{ $link->ender?->name }}</strong><p>{{ $link->end_reason }}</p>@endif @if($link->supersedes_id)<small>Substitui o vínculo #{{ $link->supersedes_id }}.</small>@endif</div></details></td>
<td>@if($resource==='alunos' && !$link->ended_at)@can('vinculos.gerenciar')<div class="row-actions">@if($person->active && $related->active)<button class="text-link" wire:click="editLink({{ $link->id }})">Alterar</button>@endif<button class="text-link" wire:click="confirmEnd({{ $link->id }})">Encerrar</button></div>@else — @endcan @elseif($resource==='responsaveis')<a class="text-link" href="{{ route('people.show',['alunos',$link->student_id]) }}">Ficha do aluno</a>@else — @endif</td></tr>
@empty<tr><td colspan="6"><div class="empty-state"><x-icon name="users"/><h3>Nenhum vínculo {{ $tab==='current' ? 'vigente' : 'registrado' }}</h3><p>{{ $resource==='alunos' ? 'Vincule um responsável para organizar o atendimento ao aluno.' : 'Os vínculos são criados a partir da ficha de cada aluno.' }}</p></div></td></tr>@endforelse
</tbody></table></div>@include('components.pagination',['paginator'=>$links])</section>@endif
</div>
